### ISSUE TITLE
Write git diff to file

### ISSUE THREAD

**Issue by martinengelcke** [akosiorek/forge#10]
In case an experiment is run without committed changes, writing 'git diff' to file ensures it is still reproducible.

**Comment by akosiorek** [comment]
That's a great idea. Alternatively, we could make (detatched) commit with the untracked changes and restore the environment after running the experiment. What do you think?

**Comment by martinengelcke** [comment]
Nice, point being that you can checkout the commit to resume from checkpoint? Maybe have a dedicated branch for these commits called forge_exp or similar?

**Comment by martinengelcke** [comment]
In the meantime, I have pushed my quick solution to a separate branch:
https://github.com/akosiorek/forge/commit/af7f7da97605275c4d10ab99444809cd195a61ba

Would need some more time to implement your proposal. Could merge the above until we have something better. Want me to create a PR?

**Comment by akosiorek** [comment]
Yeah, it's good as a temporary solution. We don't need any branch for detached commits - the'd be just hanging.

**Comment by martinengelcke** [comment]
Ok, created a PR. I am not really familiar with detached commits but that sounds easier

**Comment by akosiorek** [comment]
I'll close it for now; we can reopen if we decide to do detached commits.
