### ISSUE TITLE
Thread Safety of `os.listdir`

### ISSUE THREAD

**Issue by yassersouri** [akosiorek/forge#14]
When you are trying to find which run_name to use, you use `os.listdir`:

https://github.com/akosiorek/forge/blob/3f1ea59278b6f948e08c0a4884841e244869fb0c/forge/experiment_tools.py#L150

But this is not thread safe, so if you run this in parallel on the same filesystem, it might overwrite itself.

I have tried to implement something similar to this and actually I have run into this problem multiple times. I was wondering if you have looked for a solution to this or do you think we should just ignore this and try to work around the problem?

**Comment by akosiorek** [comment]
I haven't thought about or had issues with it before. I think that [lock files](https://en.wikipedia.org/wiki/File_locking#Lock_files) is a standard solution used by e.g. apt on Linux. You could try to implement something similar (or use [fasteners](https://pypi.org/project/fasteners/)) and submit a pull request.

**Comment by yassersouri** [comment]
Thanks. I will take a look into fasteners.
